name: PR Check

on:
  push:
    branches:
    - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: generate-tag                                                                 
      run: |                                                                             
        echo "TAG=$(git show -s --date=format:'%Y%m%d-%H%M' --format=%cd)" >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish docker plugin
      env:
        REPO: ghcr.io/${{ github.repository }}
        VERSION: ${{ env.TAG }}
      run: |
        make plugin
        docker plugin push "$REPO:$VERSION"
